name: ecc_app_school_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  go_router: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  go_router_builder: ^1.0.15

flutter:
  uses-material-design: true
